name: Test Minitest

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
    - README.md
    - LICENSE

jobs:
  test:
    name: Run tests
    runs-on: [self-hosted, linux, ARM64]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.2.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0

    - name: Minitest
      run: rake test
